apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller-kubebuilder-controller-manager-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list", "watch", "get", "create", "update"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list", "watch", "get", "create", "update"]
