apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller-kubebuilder-controller-manager-binding
subjects:
  - kind: ServiceAccount
    name: controller-kubebuilder-controller-manager
    namespace: controller-kubebuilder-system
roleRef:
  kind: ClusterRole
  name: controller-kubebuilder-controller-manager-role
  apiGroup: rbac.authorization.k8s.io
