# permissions for end users to view bookservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: bookserver-viewer-role
rules:
- apiGroups:
  - crd.sabbir.com
  resources:
  - bookservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.sabbir.com
  resources:
  - bookservers/status
  verbs:
  - get
