# permissions for end users to edit customkinds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: customkind-editor-role
rules:
- apiGroups:
  - crd.sabbir.com
  resources:
  - customkinds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.sabbir.com
  resources:
  - customkinds/status
  verbs:
  - get
