apiVersion: crd.sabbir.com/v1alpha1
kind: Customkind
metadata:
  labels:
    app.kubernetes.io/name: controller-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: customkind-sample
spec:
  replicas: 10
  container:
    image: sabbir70/api-bookserver
    port: 3000
  service:
    serviceType: "NodePort"
  # TODO(user): Add fields here
